<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="myEcore" nsURI="http://www.example.org/myEcore" nsPrefix="myEcore">    
    <eClassifiers xsi:type="ecore:EClass" name="Lonely">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_one" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt" iD="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_two" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt" iD="true"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
