<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="myEcore" nsURI="http://www.example.org/myEcore" nsPrefix="myEcore"/>
  <ecore:EPackage name="myEcore" nsURI="http://www.example.org/myEcore" nsPrefix="myEcore">
    <eClassifiers xsi:type="ecore:EClass" name="AbstractClass" abstract="true" eSuperTypes="#/1/Interface1 #/1/Interface2">
      <eStructuralFeatures xsi:type="ecore:EReference" name="subpackeclass1" upperBound="-1"
          eType="#/1/subPackage1/SubPackEClass1" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Interface1" abstract="true" interface="true">
      <eOperations name="interfaceOperation" eType="#/1/subPackage1/InnerDataType1">
        <eParameters name="parameter1" eType="#/1/ConcreteClass1"/>
        <eParameters name="parameter2" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subpackeclass2" eType="#/1/subPackage2/SubPackEClass2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Interface2" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_two" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
          iD="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConcreteClass2" eSuperTypes="#/1/AbstractClass">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_one" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SingleClass1">
      <eStructuralFeatures xsi:type="ecore:EReference" name="myclassref1" lowerBound="2"
          eType="#/1/ConcreteClass2" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="singleclass2" eType="#/1/SingleClass2"
          eOpposite="#/1/SingleClass2/singleclass1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="newAttribute" eType="#/1/subPackage1/subPackEnum1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="newAttribute2" eType="#/1/subPackage1/subPackEnum1"
          defaultValueLiteral="LITERAL0"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="diamondtop" upperBound="-1"
          eType="#/1/DiamondTop" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SingleClass2">
      <eStructuralFeatures xsi:type="ecore:EReference" name="myclassref2" lowerBound="-1"
          upperBound="10" eType="#/1/ConcreteClass2" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="childAtt" eType="#/1/subPackage1/InnerDataType1"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="singleclass1" eType="#/1/SingleClass1"
          eOpposite="#/1/SingleClass1/singleclass2"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="diamondtop" upperBound="-1"
          eType="#/1/DiamondTop" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConcreteClass1" eSuperTypes="#/1/AbstractClass">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" lowerBound="2"
          eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="newAttribute" lowerBound="12"
          upperBound="5" eType="#/1/OuterDatatype" defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="composition" lowerBound="12"
          upperBound="5" eType="#/1/ConcreteClass2" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="s" lowerBound="5" upperBound="12"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="OuterDatatype" instanceTypeName="newDataType1"/>
    <eClassifiers xsi:type="ecore:EClass" name="LonlyClass" eSuperTypes="#/1/Interface1">
      <eTypeParameters name="LonlyTypeParameter"/>
      <eOperations name="newOperation1">
        <eParameters name="para1" eType="#/1/SingleClass1"/>
        <eParameters name="para2" eType="#/1/DataClass2"/>
      </eOperations>
      <eOperations name="newOperation2">
        <eParameters name="para1" eType="#/1/SingleClass1"/>
        <eParameters name="para2" eType="#/1/DataClass2"/>
      </eOperations>
      <eOperations name="newOperation3">
        <eParameters name="para1" eType="#/1/SingleClass1"/>
        <eParameters name="para2" eType="#/1/DataClass2"/>
      </eOperations>
      <eOperations name="newOperation4">
        <eParameters name="para1" eType="#/1/SingleClass1"/>
        <eParameters name="para2" eType="#/1/DataClass2"/>
      </eOperations>
      <eOperations name="newOperation5">
        <eParameters name="para1" eType="#/1/SingleClass1"/>
        <eParameters name="para2" eType="#/1/DataClass2"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="myInt" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
          iD="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataClass1">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="myInt" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="myEString" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="myShort" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EShort"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="myString" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="myEBoolean" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="myEBooleanObject" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="myBoolean" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataClass2">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="myEBooleanObject" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="myBoolean" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="myEString" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="myString" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="myEBoolean" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="myInt" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="myShort" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EShort"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="EInt" instanceTypeName="newDataType2"/>
    <eClassifiers xsi:type="ecore:EClass" name="Parent"/>
    <eClassifiers xsi:type="ecore:EClass" name="Child3">
      <eStructuralFeatures xsi:type="ecore:EReference" name="child3" eType="#/1/Parent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Child1">
      <eStructuralFeatures xsi:type="ecore:EReference" name="child1" eType="#/1/Parent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Child2">
      <eStructuralFeatures xsi:type="ecore:EReference" name="child2" eType="#/1/Parent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Child4">
      <eStructuralFeatures xsi:type="ecore:EReference" name="child4" eType="#/1/Parent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Child5">
      <eStructuralFeatures xsi:type="ecore:EReference" name="child5" eType="#/1/Parent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Child1">
      <eStructuralFeatures xsi:type="ecore:EReference" name="child1" eType="#/1/Parent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Child2">
      <eStructuralFeatures xsi:type="ecore:EReference" name="child2" eType="#/1/Parent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiamondTop"/>
    <eClassifiers xsi:type="ecore:EClass" name="DiamondRight" eSuperTypes="#/1/DiamondTop"/>
    <eClassifiers xsi:type="ecore:EClass" name="DiamondBottom" eSuperTypes="#/1/DiamondRight #/1/DiamondLeft"/>
    <eClassifiers xsi:type="ecore:EClass" name="DiamondLeft" eSuperTypes="#/1/DiamondTop">
      <eStructuralFeatures xsi:type="ecore:EReference" name="concreteclass1"/>
    </eClassifiers>
    <eSubpackages name="subPackage1">
      <eClassifiers xsi:type="ecore:EClass" name="SubPackEClass1">
        <eOperations name="newOperation1" eType="#/1/subPackage2/SubPackEClass2"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
            iD="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="newAttribute" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
            iD="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="subPackEnum1">
        <eLiterals name="LITERAL0"/>
        <eLiterals name="LITERAL1" value="1"/>
        <eLiterals name="LITERAL2" value="2"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EDataType" name="InnerDataType1" instanceTypeName="newDataType2"/>
    </eSubpackages>
    <eSubpackages name="subPackage2">
      <eClassifiers xsi:type="ecore:EClass" name="SubPackEClass2">
        <eOperations name="subPackOperation1" eType="#/1/OuterDatatype"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
            iD="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="newAttribute" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
            iD="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="newAttribute2" eType="#/1/subPackage1/subPackEnum1"
            defaultValueLiteral="LITERAL0"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="">
      <eClassifiers xsi:type="ecore:EClass" name=""/>
    </eSubpackages>
  </ecore:EPackage>
</xmi:XMI>
